"use client";

import {useEffect,useMemo,useState} from "react";
import {Area,AreaChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {CalendarDays,Download,FilePenLine,FileText,PackageCheck,RefreshCw,Save,Users,X} from "lucide-react";
import type {MonthlyData,MonthlyReport} from "@/types/analytics";
import {PageHeading} from "@/components/customer-dashboard";

const number=(value:number)=>new Intl.NumberFormat("ko-KR").format(value);
const emptyReport=(month:string):MonthlyReport=>({report_month:month,current_sales:0,previous_sales:0,issues:[],actions:[],results:[],next_month_plan:"",partner_requests:"",updated_at:new Date().toISOString()});
const previousMonthKey=(month:string)=>{const [year,mon]=month.split("-").map(Number);const date=new Date(year,mon-2,1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`};

export function MonthlyDashboard({range}:{range?:{from:string;to:string}}){
  const [data,setData]=useState<MonthlyData|null>(null);const [error,setError]=useState("");const [editing,setEditing]=useState(false);const [saving,setSaving]=useState(false);const [draft,setDraft]=useState<MonthlyReport|null>(null);
  const load=()=>fetch("/api/monthly",{cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);setData(result)}).catch(reason=>setError(reason instanceof Error?reason.message:"월간 데이터를 불러오지 못했습니다."));
  useEffect(()=>{void load()},[]);
  const trends=useMemo(()=>data?.trends.filter(row=>(!range?.from||row.month>=range.from.slice(0,7))&&(!range?.to||row.month<=range.to.slice(0,7)))??[],[data,range?.from,range?.to]);
  const latest=trends.at(-1);const previous=trends.at(-2);const month=latest?.month??range?.to?.slice(0,7)??"";const report=data?.reports.find(row=>row.report_month===month);const change=latest&&previous&&previous.orders?(latest.orders-previous.orders)/previous.orders*100:0;
  const edit=()=>{const previousReport=data?.reports.find(row=>row.report_month===previousMonthKey(month));setDraft(report?{...report}:{...emptyReport(month),previous_sales:previousReport?.current_sales??0});setEditing(true)};
  const save=async()=>{if(!draft)return;setSaving(true);const response=await fetch("/api/monthly",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save",report:draft})});if(response.ok){await load();setEditing(false)}else setError((await response.json()).error);setSaving(false)};
  const download=async(format:"xlsx"|"pdf")=>{const response=await fetch("/api/monthly",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"export",month,format,report:draft??report??emptyReport(month)})});const result=await response.json();if(!response.ok){setError(result.error);return}const bytes=Uint8Array.from(atob(result.content),(char)=>char.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:format==="pdf"?"application/pdf":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}));const link=document.createElement("a");link.href=url;link.download=result.filename;link.click();URL.revokeObjectURL(url)};
  if(error)return <div className="rounded-xl border border-red-200 bg-red-50 p-5 text-red-700">{error}</div>;if(!data)return <div className="grid min-h-[60vh] place-items-center"><RefreshCw className="animate-spin"/></div>;
  return <>
    <div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><PageHeading eyebrow="MONTHLY REPORT" title="월간리포트" description="월간 운영 현황을 먼저 확인하고 필요할 때 보고서를 입력·수정합니다."/><div className="flex gap-2"><button onClick={()=>download("xlsx")} className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm dark:border-slate-700"><Download size={16}/>Excel</button><button onClick={()=>download("pdf")} className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm dark:border-slate-700"><Download size={16}/>PDF</button><button onClick={edit} className="flex items-center gap-2 rounded-xl bg-[#13263d] px-4 py-2.5 text-sm font-semibold text-white dark:bg-[#09182B]"><FilePenLine size={16}/>입력·수정</button></div></div>
    <div className="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric icon={CalendarDays} label="기준 월" value={month||"데이터 없음"} note="선택 조회기간"/><Metric icon={FileText} label="월 주문 건수" value={`${number(latest?.orders??0)}건`} note={`${change>=0?"+":""}${change.toFixed(1)}% 전월 대비`}/><Metric icon={Users} label="활성 고객" value={`${number(latest?.customers??0)}명`} note="해당 월 주문 고객"/><Metric icon={PackageCheck} label="주문 수량" value={`${number(latest?.quantity??0)}개`} note="월 누적 수량"/></div>
    <div className="card mb-6 p-6"><h2 className="text-lg font-bold">월간 운영 추이</h2><p className="mb-5 mt-1 text-sm text-slate-500">주문 건수와 활성 고객 변화</p><ResponsiveContainer width="100%" height={350}><AreaChart data={trends}><defs><linearGradient id="monthly-orders" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--chart-accent)" stopOpacity={.3}/><stop offset="95%" stopColor="var(--chart-accent)" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Area dataKey="orders" name="주문 건수" stroke="var(--chart-accent)" fill="url(#monthly-orders)"/><Area dataKey="customers" name="활성 고객" stroke="#94a3b8" fill="transparent"/></AreaChart></ResponsiveContainer></div>
    <div className="card p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">{month} 운영보고서</h2><p className="mt-1 text-sm text-slate-500">자동 지표와 작성 내용을 결재 문서로 출력합니다.</p></div><span className={`rounded-full px-3 py-1 text-xs ${report?"bg-emerald-100 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{report?"작성 완료":"미작성"}</span></div>{report?<div className="mt-6 grid gap-4 md:grid-cols-3"><ReportBlock title="당월 주요 이슈" rows={report.issues}/><ReportBlock title="조치 내역 및 결과" rows={report.actions.map((row,index)=>`${row}${report.results[index]?` → ${report.results[index]}`:""}`)}/><ReportBlock title="협력사 요청" rows={[report.partner_requests]}/><ReportBlock title="익월 계획" rows={[report.next_month_plan]}/><ReportBlock title="매출 (전월 대비)" rows={[`당월 ${number(report.current_sales)}원`,`전월 ${number(report.previous_sales)}원`,report.previous_sales?`${report.current_sales>=report.previous_sales?"+":""}${((report.current_sales-report.previous_sales)/report.previous_sales*100).toFixed(1)}% 전월 대비`:"전월 매출 없음"]}/><ReportBlock title="회원 현황" rows={[`전체 회원 ${number(data?.total_members??0)}명`,`당월 주문 고객 ${number(latest?.customers??0)}명`,`당월 주문 수량 ${number(latest?.quantity??0)}개 · 주문 ${number(latest?.orders??0)}건`]}/></div>:<div className="py-12 text-center text-sm text-slate-400">작성된 보고서가 없습니다. 주문·회원 지표는 위 대시보드에서 자동 집계됩니다.</div>}</div>
    {editing&&draft&&<div className="fixed inset-0 z-50 flex justify-end bg-black/45"><div className="h-full w-full max-w-2xl overflow-auto bg-white p-7 shadow-2xl dark:bg-[#101C2E]"><div className="mb-7 flex items-center justify-between"><div><h2 className="text-xl font-bold">{month} 보고서 입력·수정</h2><p className="mt-1 text-xs text-slate-500">매출은 원본에 금액 컬럼이 없어 직접 입력합니다.</p></div><button onClick={()=>setEditing(false)}><X/></button></div><div className="grid gap-4 sm:grid-cols-2"><NumberField label="당월 매출" value={draft.current_sales} onChange={value=>setDraft({...draft,current_sales:value})}/><NumberField label="전월 매출" value={draft.previous_sales} onChange={value=>setDraft({...draft,previous_sales:value})}/></div><TextField label="당월 주요 이슈" value={draft.issues.join("\n")} onChange={value=>setDraft({...draft,issues:value.split("\n").filter(Boolean)})}/><TextField label="이슈별 조치 내역" value={draft.actions.join("\n")} onChange={value=>setDraft({...draft,actions:value.split("\n").filter(Boolean)})}/><TextField label="조치 결과" value={draft.results.join("\n")} onChange={value=>setDraft({...draft,results:value.split("\n").filter(Boolean)})}/><TextField label="익월 계획" value={draft.next_month_plan} onChange={value=>setDraft({...draft,next_month_plan:value})}/><TextField label="협력사 요청 사항" value={draft.partner_requests} onChange={value=>setDraft({...draft,partner_requests:value})}/><button onClick={save} disabled={saving} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#13263d] py-3 font-semibold text-white dark:bg-[#09182B]"><Save size={17}/>{saving?"저장 중":"보고서 저장"}</button></div></div>}
  </>;
}
function Metric({icon:Icon,label,value,note}:{icon:typeof Users;label:string;value:string;note:string}){return <div className="card p-5"><div className="flex justify-between"><span className="text-sm text-slate-500">{label}</span><Icon className="text-amber-600" size={18}/></div><div className="mt-3 text-2xl font-bold">{value}</div><div className="mt-2 text-xs text-slate-400">{note}</div></div>}
function ReportBlock({title,rows}:{title:string;rows:string[]}){return <div className="rounded-xl bg-slate-50 p-4 dark:bg-[#0B1B30]"><b className="text-xs text-slate-500">{title}</b><ul className="mt-2 space-y-1 text-sm">{rows.filter(Boolean).map((row,index)=><li key={index}>• {row}</li>)}</ul></div>}
function TextField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="mt-5 block"><span className="mb-2 block text-sm font-semibold">{label}</span><textarea value={value} onChange={event=>onChange(event.target.value)} rows={3} className="w-full rounded-xl border border-slate-200 bg-transparent p-3 text-sm outline-none focus:border-amber-500 dark:border-slate-700" placeholder="한 줄에 한 항목씩 입력"/></label>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label><span className="mb-2 block text-sm font-semibold">{label}</span><input type="number" min="0" value={value} onChange={event=>onChange(Number(event.target.value)||0)} className="w-full rounded-xl border border-slate-200 bg-transparent p-3 text-sm dark:border-slate-700"/></label>}
